CREATE DATABASE IF NOT EXISTS sheldon CHARACTER SET utf8 COLLATE utf8_general_ci;

USE sheldon;

CREATE TABLE IF NOT EXISTS players (
    id INT(10) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS games (
    id INT(10) AUTO_INCREMENT PRIMARY KEY,
    winner_id INT(10) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (winner_id) REFERENCES players(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS game_decisions (
    id INT(10) AUTO_INCREMENT PRIMARY KEY,
    player_id INT(10) NOT NULL,
    game_id INT(10) NOT NULL,
    decision ENUM('rock', 'paper', 'scissors', 'lizard', 'spock') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE,
    FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);